name: render page
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # every week on Sunday
    - cron: "0 0 * * 0"

jobs:
  update_repo_info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: |
        pip install -r requirements.txt
        python scripts/parse_gh_api.py
    - name: Update Repo List
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update repo list"
        add: "docs/assets/cards/repos.json"
        committer_name: "GitHub Actions"
        committer_email: "actions@github.com"
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: |
        mkdocs gh-deploy --force
